name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    services:
      ml:
        image: python:3.11
        env: {}
        ports:
          - 8000:8000
        options: >-
          --health-cmd "curl -f http://localhost:8000/health || exit 1" --health-interval 10s --health-retries 5 --health-timeout 5s
        command: ["bash", "-c", "pip install fastapi uvicorn scikit-learn numpy sentence-transformers hdbscan bs4 cachetools && uvicorn app.main:app --host 0.0.0.0 --port 8000 --app-dir ml-service/app"]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install node deps
        run: npm install
      - name: Install python deps (for local ml usage)
        run: |
          python -m pip install --upgrade pip
          pip install -r ml-service/requirements.txt || true
      - name: Build packages
        run: npm run build
      - name: Run tests
        run: npm test
      - name: Playwright Browsers
        run: npx playwright install --with-deps chromium
      - name: Run E2E (headless)
        env:
          ML_URL: http://localhost:8000
        run: npx playwright test --project=chromium || true
